runtime: php
env: flex
service: wordpress

beta_settings:
  cloud_sql_instances: "wordpress-test-222422:us-central1:wordpress"

runtime_config:
  document_root: .

env_variables:
  WHITELIST_FUNCTIONS: escapeshellarg,escapeshellcmd,exec,pclose,popen,shell_exec,phpversion,php_uname
  FRONTEND_URL: https://frontend-dot-wordpress-test-222422.appspot.com
